CREATE TABLE CUSTOMER_INFORMATION
(
RELATE_INTEGRATION_ID  INT  NOT  NULL  IDENTITY(1,1)  CONSTRAINT PK_OCP_RELATE_INTEGRATION_ID  PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
FIRST_NAME VARCHAR(50) NULL,
LAST_NAME VARCHAR(50) NULL,
ADDRESS_LINE_1 VARCHAR(255) NULL,
ADDRESS_LINE_2 VARCHAR(255) NULL,
CITY VARCHAR(50) NULL,
STATE VARCHAR(50) NULL,
COUNTRY VARCHAR(50) NULL,
ZIP_CODE VARCHAR(12) NULL,
EMAIL_OPT_IN_STATUS VARCHAR(1) NULL,
PHONE_NUMBER VARCHAR(20) NULL,
LAST_UPDATED_TIME DATETIME NULL,
EXIST_IN_RELATE VARCHAR(1) NULL,
OBSESSION_CLOTHES VARCHAR(1) NULL ,
OBSESSION_ACCESSORIES VARCHAR(1) NULL ,
OBSESSION_SHOES VARCHAR(1) NULL ,
OBSESSION_FASHION VARCHAR(1) NULL ,
OCP_CUST_ID VARCHAR(15) NULL
)

CREATE TABLE PHONE_SUBSCRIPTION
(
	PHONE_NUMBER NUMERIC(10,0) NOT NULL PRIMARY KEY,
	PHONE_OPT_IN_STATUS VARCHAR(1) NULL,
	LAST_UPDATED_TIME DATETIME NULL
)


