//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.31 at 12:23:47 PM IST 
//


package com.rim.integration.xml.customer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Customer element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Customer">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="LastUpdateInfo" type="{}LastUpdateInfoType"/>
 *           &lt;element name="RetailStoreID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="SignupDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *           &lt;element name="CustomerNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CustomerReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="OrgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CustOrgTypcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="EmployeeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="Affiliation" type="{}AffiliationType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Prospect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *           &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="BusinessName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CustomerClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="EntityInformation" type="{}EntityInformationType"/>
 *           &lt;element name="PersonalPreferences" type="{}PersonalPreferencesType"/>
 *           &lt;element name="AlternateKey" type="{}AlternateKeyType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="CustomAttribute" type="{}CustomAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="CustomerNotes" type="{}CustomerNotesContainerType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="Action" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lastUpdateInfo",
    "retailStoreID",
    "signupDate",
    "customerNumber",
    "customerReference",
    "orgName",
    "custOrgTypcode",
    "employeeID",
    "affiliation",
    "prospect",
    "source",
    "businessName",
    "customerClass",
    "entityInformation",
    "personalPreferences",
    "alternateKey",
    "customAttribute",
    "customerNotes"
})
@XmlRootElement(name = "Customer")
public class Customer {

    @XmlElement(name = "LastUpdateInfo", required = true)
    protected LastUpdateInfoType lastUpdateInfo;
    @XmlElement(name = "RetailStoreID", required = true)
    protected String retailStoreID;
    @XmlElement(name = "SignupDate")
    protected XMLGregorianCalendar signupDate;
    @XmlElement(name = "CustomerNumber", required = true)
    protected String customerNumber;
    @XmlElement(name = "CustomerReference", required = true)
    protected String customerReference;
    @XmlElement(name = "OrgName", required = true)
    protected String orgName;
    @XmlElement(name = "CustOrgTypcode", required = true)
    protected String custOrgTypcode;
    @XmlElement(name = "EmployeeID", required = true)
    protected String employeeID;
    @XmlElement(name = "Affiliation", required = true)
    protected List<AffiliationType> affiliation;
    @XmlElement(name = "Prospect")
    protected Boolean prospect;
    @XmlElement(name = "Source", required = true)
    protected String source;
    @XmlElement(name = "BusinessName", required = true)
    protected String businessName;
    @XmlElement(name = "CustomerClass", required = true)
    protected String customerClass;
    @XmlElement(name = "EntityInformation", required = true)
    protected EntityInformationType entityInformation;
    @XmlElement(name = "PersonalPreferences", required = true)
    protected PersonalPreferencesType personalPreferences;
    @XmlElement(name = "AlternateKey", required = true)
    protected List<AlternateKeyType> alternateKey;
    @XmlElement(name = "CustomAttribute", required = true)
    protected List<CustomAttributeType> customAttribute;
    @XmlElement(name = "CustomerNotes")
    protected CustomerNotesContainerType customerNotes;
    @XmlAttribute(name = "Action", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String action;

    /**
     * Gets the value of the lastUpdateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LastUpdateInfoType }
     *     
     */
    public LastUpdateInfoType getLastUpdateInfo() {
        return lastUpdateInfo;
    }

    /**
     * Sets the value of the lastUpdateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LastUpdateInfoType }
     *     
     */
    public void setLastUpdateInfo(LastUpdateInfoType value) {
        this.lastUpdateInfo = value;
    }

    /**
     * Gets the value of the retailStoreID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailStoreID() {
        return retailStoreID;
    }

    /**
     * Sets the value of the retailStoreID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailStoreID(String value) {
        this.retailStoreID = value;
    }

    /**
     * Gets the value of the signupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignupDate() {
        return signupDate;
    }

    /**
     * Sets the value of the signupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignupDate(XMLGregorianCalendar value) {
        this.signupDate = value;
    }

    /**
     * Gets the value of the customerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the customerReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerReference() {
        return customerReference;
    }

    /**
     * Sets the value of the customerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerReference(String value) {
        this.customerReference = value;
    }

    /**
     * Gets the value of the orgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

    /**
     * Gets the value of the custOrgTypcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustOrgTypcode() {
        return custOrgTypcode;
    }

    /**
     * Sets the value of the custOrgTypcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustOrgTypcode(String value) {
        this.custOrgTypcode = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the affiliation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAffiliation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffiliationType }
     * 
     * 
     */
    public List<AffiliationType> getAffiliation() {
        if (affiliation == null) {
            affiliation = new ArrayList<AffiliationType>();
        }
        return this.affiliation;
    }

    /**
     * Gets the value of the prospect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProspect() {
        return prospect;
    }

    /**
     * Sets the value of the prospect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProspect(Boolean value) {
        this.prospect = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the customerClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerClass() {
        return customerClass;
    }

    /**
     * Sets the value of the customerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerClass(String value) {
        this.customerClass = value;
    }

    /**
     * Gets the value of the entityInformation property.
     * 
     * @return
     *     possible object is
     *     {@link EntityInformationType }
     *     
     */
    public EntityInformationType getEntityInformation() {
        return entityInformation;
    }

    /**
     * Sets the value of the entityInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityInformationType }
     *     
     */
    public void setEntityInformation(EntityInformationType value) {
        this.entityInformation = value;
    }

    /**
     * Gets the value of the personalPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalPreferencesType }
     *     
     */
    public PersonalPreferencesType getPersonalPreferences() {
        return personalPreferences;
    }

    /**
     * Sets the value of the personalPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalPreferencesType }
     *     
     */
    public void setPersonalPreferences(PersonalPreferencesType value) {
        this.personalPreferences = value;
    }

    /**
     * Gets the value of the alternateKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternateKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternateKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlternateKeyType }
     * 
     * 
     */
    public List<AlternateKeyType> getAlternateKey() {
        if (alternateKey == null) {
            alternateKey = new ArrayList<AlternateKeyType>();
        }
        return this.alternateKey;
    }

    /**
     * Gets the value of the customAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomAttributeType }
     * 
     * 
     */
    public List<CustomAttributeType> getCustomAttribute() {
        if (customAttribute == null) {
            customAttribute = new ArrayList<CustomAttributeType>();
        }
        return this.customAttribute;
    }

    /**
     * Gets the value of the customerNotes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerNotesContainerType }
     *     
     */
    public CustomerNotesContainerType getCustomerNotes() {
        return customerNotes;
    }

    /**
     * Sets the value of the customerNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerNotesContainerType }
     *     
     */
    public void setCustomerNotes(CustomerNotesContainerType value) {
        this.customerNotes = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
