//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.31 at 12:23:47 PM IST 
//


package com.rim.integration.xml.customer;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for NameLocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NameLocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="First"/>
 *     &lt;enumeration value="First2"/>
 *     &lt;enumeration value="Middle"/>
 *     &lt;enumeration value="Last"/>
 *     &lt;enumeration value="Last2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum NameLocationType {

    @XmlEnumValue("First")
    FIRST("First"),
    @XmlEnumValue("First2")
    FIRST_2("First2"),
    @XmlEnumValue("Last")
    LAST("Last"),
    @XmlEnumValue("Last2")
    LAST_2("Last2"),
    @XmlEnumValue("Middle")
    MIDDLE("Middle");
    private final String value;

    NameLocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NameLocationType fromValue(String v) {
        for (NameLocationType c: NameLocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
