//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.31 at 12:23:47 PM IST 
//


package com.rim.integration.xml.customer;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rim.integration.xml.customer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rim.integration.xml.customer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityInformationType }
     * 
     */
    public EntityInformationType createEntityInformationType() {
        return new EntityInformationType();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link SocioEconomicProfileType }
     * 
     */
    public SocioEconomicProfileType createSocioEconomicProfileType() {
        return new SocioEconomicProfileType();
    }

    /**
     * Create an instance of {@link TelephoneType }
     * 
     */
    public TelephoneType createTelephoneType() {
        return new TelephoneType();
    }

    /**
     * Create an instance of {@link EMailType }
     * 
     */
    public EMailType createEMailType() {
        return new EMailType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CustomerNameType }
     * 
     */
    public CustomerNameType createCustomerNameType() {
        return new CustomerNameType();
    }

    /**
     * Create an instance of {@link ContactInformationType }
     * 
     */
    public ContactInformationType createContactInformationType() {
        return new ContactInformationType();
    }

    /**
     * Create an instance of {@link CustomerNotesContainerType }
     * 
     */
    public CustomerNotesContainerType createCustomerNotesContainerType() {
        return new CustomerNotesContainerType();
    }

    /**
     * Create an instance of {@link CustomAttributeType }
     * 
     */
    public CustomAttributeType createCustomAttributeType() {
        return new CustomAttributeType();
    }

    /**
     * Create an instance of {@link CustomerNameTypeEntry }
     * 
     */
    public CustomerNameTypeEntry createCustomerNameTypeEntry() {
        return new CustomerNameTypeEntry();
    }

    /**
     * Create an instance of {@link AlternateKeyType }
     * 
     */
    public AlternateKeyType createAlternateKeyType() {
        return new AlternateKeyType();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link ContactPreferenceType }
     * 
     */
    public ContactPreferenceType createContactPreferenceType() {
        return new ContactPreferenceType();
    }

    /**
     * Create an instance of {@link LastUpdateInfoType }
     * 
     */
    public LastUpdateInfoType createLastUpdateInfoType() {
        return new LastUpdateInfoType();
    }

    /**
     * Create an instance of {@link IndividualType }
     * 
     */
    public IndividualType createIndividualType() {
        return new IndividualType();
    }

    /**
     * Create an instance of {@link PersonalPreferencesType }
     * 
     */
    public PersonalPreferencesType createPersonalPreferencesType() {
        return new PersonalPreferencesType();
    }

    /**
     * Create an instance of {@link AffiliationType }
     * 
     */
    public AffiliationType createAffiliationType() {
        return new AffiliationType();
    }

    /**
     * Create an instance of {@link CustomerNotesType }
     * 
     */
    public CustomerNotesType createCustomerNotesType() {
        return new CustomerNotesType();
    }

    /**
     * Create an instance of {@link PersonalSummaryType }
     * 
     */
    public PersonalSummaryType createPersonalSummaryType() {
        return new PersonalSummaryType();
    }

}
