//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.31 at 12:23:47 PM IST 
//


package com.rim.integration.xml.customer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SocioEconomicProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocioEconomicProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HighestEducationalLevelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnnualIncomeAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NetWorth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocioEconomicProfileType", propOrder = {
    "highestEducationalLevelName",
    "annualIncomeAmount",
    "netWorth"
})
public class SocioEconomicProfileType {

    @XmlElement(name = "HighestEducationalLevelName", required = true)
    protected String highestEducationalLevelName;
    @XmlElement(name = "AnnualIncomeAmount", required = true)
    protected String annualIncomeAmount;
    @XmlElement(name = "NetWorth", required = true)
    protected String netWorth;

    /**
     * Gets the value of the highestEducationalLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighestEducationalLevelName() {
        return highestEducationalLevelName;
    }

    /**
     * Sets the value of the highestEducationalLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighestEducationalLevelName(String value) {
        this.highestEducationalLevelName = value;
    }

    /**
     * Gets the value of the annualIncomeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnualIncomeAmount() {
        return annualIncomeAmount;
    }

    /**
     * Sets the value of the annualIncomeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnualIncomeAmount(String value) {
        this.annualIncomeAmount = value;
    }

    /**
     * Gets the value of the netWorth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetWorth() {
        return netWorth;
    }

    /**
     * Sets the value of the netWorth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetWorth(String value) {
        this.netWorth = value;
    }

}
